config/routes.rb
Rails.application.routes.draw do


root to:  'static_pages#home', as: :home

  get 'signup', to: 'users#new', as: :signup
  get 'users', to: 'users#index', as: :club
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

validates :first_name, presence: true, length: { maximum: 50 }

validates :last_name, presence: true, length: { maximum: 50 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false }


validates :password, presence: true, length: { minimum: 6 }
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
        log_in(user)
        redirect_to user_path(current_user.id)
        else
        flash.now[:danger] = 'Email et/ou mot de passe invalide'
        render 'new'
        end
    end

    def destroy
      log_out
      redirect_to home_path
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if logged_in?
    @users = User.all
    render 'index'
  else
    flash[:danger] ='Vous devez vous connecter pour accéder à la page'
    redirect_to login_path
  end
end

  # GET /users/1
  # GET /users/1.json
  def show
      if current_user.nil?
      flash[:danger] = 'Vous devez vous connecter pour accéder à cette page !'
      redirect_to login_path
    elsif current_user.id == params[:id].to_i
      @user = User.find(params[:id])
      render 'show'
    else
      flash[:danger] = 'Vous devez vous connecter pour accéder à cette page !'
      redirect_to login_path
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'Vous avez bien créé votre compte' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to login_url, notice: 'Vos modifications ont bien été enregistrées' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
# Méthode qui permet de démarrer une session (qui sera enregistrée dans le navigateur de l’utilisateur)
 def log_in(user)
      session[:user_id] = user.id
  end

  # Méthode qui permet de vérifier à chaque changement de page, si un utilisateur a une session en cours
  def current_user
      if @current_user.nil?
       @current_user = User.find_by(id: session[:user_id])
       else
      @current_user
      end
  end

  # Méthode qui détermine si un utilisateur est déjà connecté, renvoie true si l’utilisateur est connecté, sera utilisée pour l’affichage de la nav bar
  def logged_in?
      !current_user.nil?
  end

  # Méthode pour déconnecter l’utilisateur de sa session
  def log_out
        session.delete(:user_id)
        @current_user = nil
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<section class="footer">
    <div class="row align-items-center">
      <div class="col-3">Projet du lundi, tête à l'envers le mardi</div>
      <div class="col-6"><center>Projet 100% français 🇫🇷</center></div>
      <div class="col-3 right">© THP - Moussaillonne - Canicule Eté 2018 </div>
    </div>
</section>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark" >
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample10" aria-controls="navbarsExample10" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

       <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%= home_path%>">HOME<span class="sr-only">(current)</span></a>
          </li>
           <li class="nav-item active">
            <a class="nav-link" href="<%= club_path%>">LE CLUB<span class="sr-only">(current)</span></a>
          </li>
          <% if logged_in? %>
          <li class="nav-item">

            <a class="nav-link" href="<%= user_path(current_user.id) %>">Mon compte</a>
          </li>
          <li class="nav-item">
          <span class="nav-link disabled">
          <%= link_to "Se déconnecter", logout_path, method: :delete  %>
        </span>
          </li>
          <% else %>
          <li class="nav-item">
            <a class="nav-link disabled" href="<%= signup_path %>">S'inscrire</a>
          </li>
           <li class="nav-item">
            <a class="nav-link disabled" href="<%= login_path %>">Se connecter</a>
          </li>
          <% end %>

       </ul>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>ClubPrive</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="container"><br>
<br>

<h1 style="text-align: center"> 🏅 🎖 🎗 Bienvenue sur le Club Privé ⛳️ 🏌 🏆</h1>
<br>
<br>

<h2 style="text-align: center"><a href= "/signup"> Si vous souhaitez en faire partie, merci de cliquer sur ce lien </a></h2>
<br>
<br>

<span><img src="http://www.newlifealliance.net/wp-content/uploads/2017/08/secret-club.png" style="width: 30%; max-width:%; position: relative; top: 10px; bottom: 150px; left: 35%; right: 50%" alt="Club secret"></span>

</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name, "Prénom" %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name, "Nom" %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email, "Email" %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password, "Mot de passe" %>
    <%= form.password_field :password %>
  </div>

<div class="field">
    <%= form.label :password_confirmation, "Confirmation du mot de passe" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Vous pouvez modifier les infos vous concernant</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Nouveau clubber</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<h3> <%= @user.first_name %>, voici ta page: </h3>
<br>
<br>
<h5> Pour rappel, les informations que tu as complétées sont les suivantes: </h5>
<br>
<p>
  <strong>Prénom:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


Voici le lien pour accéder à la page de notre Club secret:
<%= link_to 'Cette fameuse page', club_path %>
<br>
<br>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>